# Generated by Django 5.2.7 on 2025-11-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='users_img', verbose_name='Фото'),
        ),
    ]
