# Generated by Django 5.2.7 on 2025-11-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_alter_customuser_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='familydoctor',
            name='date_of_appointment',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата призначення'),
        ),
    ]
