# Generated by Django 5.2.7 on 2025-11-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_app', '0003_alter_cardvaccine_vaccination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualmarks',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Значення'),
        ),
    ]
