# Generated by Django 5.2.7 on 2025-10-22 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards_app', '0002_initial'),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва параметру')),
                ('unit_of_measurement', models.CharField(max_length=20, verbose_name='Одиниці вимірювання')),
                ('normal_min', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Мінімально допустиме значення')),
                ('normal_max', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Максимально допустиме значення')),
            ],
            options={
                'verbose_name': 'Шаблон параметру',
                'verbose_name_plural': 'Шаблони параметрів',
                'db_table': 'TemplateParameter',
            },
        ),
        migrations.CreateModel(
            name='TypeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва аналізу')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Опис аналізу')),
            ],
            options={
                'verbose_name': 'Тип аналізу',
                'verbose_name_plural': 'Типи аналізів',
                'db_table': 'TypeAnalys',
            },
        ),
        migrations.CreateModel(
            name='MedReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення направлення')),
                ('coment', models.TextField(max_length=500, verbose_name='Коментар')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_app.doctor', verbose_name='ID лікаря')),
                ('medcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards_app.medcards', verbose_name='Номер медичної карти')),
                ('id_type_analys', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory_app.typeanalysis', verbose_name='ID типу аналізу')),
            ],
            options={
                'verbose_name': 'Направлення',
                'verbose_name_plural': 'Направлення',
                'db_table': 'MedReferral',
            },
        ),
        migrations.CreateModel(
            name='ResultAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('providing_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата видачі результату')),
                ('report', models.TextField(max_length=500, verbose_name='Висновок')),
                ('id_lab_assistent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_app.laboratoryassistent', verbose_name='ІD лаборанта')),
                ('id_medcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards_app.medcards', verbose_name='Номер медичної карти')),
                ('id_referral', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory_app.medreferral', verbose_name='ID направлення')),
            ],
            options={
                'verbose_name': 'Результат аналізу',
                'verbose_name_plural': 'Результати аналізів',
                'db_table': 'ResultAnalys',
            },
        ),
        migrations.CreateModel(
            name='ResultParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Результат')),
                ('unit_of_measurement', models.CharField(max_length=20, verbose_name='Одиниці вимірювання')),
                ('coment', models.CharField(max_length=100, verbose_name='Коментар')),
                ('id_result_analys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory_app.resultanalysis', verbose_name='ID результатів аналізів')),
                ('id_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory_app.templateparameter', verbose_name='ID шаблону аналізу')),
            ],
            options={
                'verbose_name': 'Результат параметру',
                'verbose_name_plural': 'Результати параметрів',
                'db_table': 'ResultParameter',
            },
        ),
        migrations.AddField(
            model_name='templateparameter',
            name='id_type_analys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory_app.typeanalysis', verbose_name='ID типу аналізу'),
        ),
        migrations.AlterUniqueTogether(
            name='templateparameter',
            unique_together={('name', 'id_type_analys')},
        ),
    ]
