# Generated by Django 5.2.7 on 2025-11-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory_app', '0006_alter_templateparameter_normal_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateparameter',
            name='normal_max',
            field=models.DecimalField(decimal_places=3, max_digits=9, verbose_name='Максимально допустиме значення'),
        ),
    ]
