# Generated by Django 5.2.7 on 2025-11-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory_app', '0009_alter_templateparameter_normal_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medreferral',
            name='status',
            field=models.CharField(choices=[('N', 'Активне'), ('C', 'Анульовано')], default='N', max_length=1, verbose_name='Статус направлення'),
        ),
    ]
