# Generated by Django 5.2.7 on 2025-11-11 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory_app', '0010_medreferral_status'),
        ('users_app', '0003_familydoctor_date_of_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultanalysis',
            name='lab_assistent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users_app.laboratoryassistent', verbose_name='ІD лаборанта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultanalysis',
            name='referral',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='laboratory_app.medreferral', verbose_name='ID направлення'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultparameter',
            name='unit_of_measurement',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Одиниці вимірювання'),
        ),
    ]
