# Generated by Django 5.2.7 on 2025-11-29 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory_app', '0013_typeanalysis_preparation'),
        ('users_app', '0003_familydoctor_date_of_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeanalysis',
            name='preparation',
        ),
        migrations.AlterField(
            model_name='medreferral',
            name='doctor',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='users_app.doctor', verbose_name='ID лікаря'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medreferral',
            name='type_analys',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='laboratory_app.typeanalysis', verbose_name='ID типу аналізу'),
            preserve_default=False,
        ),
    ]
