# Generated by Django 5.2.7 on 2025-10-22 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medreferral',
            old_name='id_type_analys',
            new_name='type_analys',
        ),
        migrations.RenameField(
            model_name='resultanalysis',
            old_name='id_lab_assistent',
            new_name='lab_assistent',
        ),
        migrations.RenameField(
            model_name='resultanalysis',
            old_name='id_medcard',
            new_name='medcard',
        ),
        migrations.RenameField(
            model_name='resultanalysis',
            old_name='id_referral',
            new_name='referral',
        ),
        migrations.RenameField(
            model_name='resultparameter',
            old_name='id_result_analys',
            new_name='result_analys',
        ),
        migrations.RenameField(
            model_name='resultparameter',
            old_name='id_template',
            new_name='template',
        ),
        migrations.RenameField(
            model_name='templateparameter',
            old_name='id_type_analys',
            new_name='type_analys',
        ),
        migrations.AlterUniqueTogether(
            name='templateparameter',
            unique_together={('name', 'type_analys')},
        ),
    ]
