# Generated by Django 5.2.7 on 2025-10-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory_app', '0002_rename_id_type_analys_medreferral_type_analys_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultanalysis',
            name='providing_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата заповнення виcновку'),
        ),
    ]
