# Generated by Django 5.2.7 on 2025-11-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory_app', '0005_alter_templateparameter_normal_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateparameter',
            name='normal_min',
            field=models.DecimalField(decimal_places=3, max_digits=9, verbose_name='Мінімально допустиме значення'),
        ),
    ]
