# Generated by Django 5.2.7 on 2025-11-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory_app', '0011_alter_resultanalysis_lab_assistent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateparameter',
            name='normal_max',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Максимально допустиме значення'),
        ),
        migrations.AlterField(
            model_name='templateparameter',
            name='normal_min',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Мінімально допустиме значення'),
        ),
    ]
