# Generated by Django 5.2.7 on 2025-11-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory_app', '0012_alter_templateparameter_normal_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeanalysis',
            name='preparation',
            field=models.CharField(blank=True, choices=[('fasting_12h', 'Натще (не їсти 8–12 год.)'), ('no_coffee', 'Не пити каву, чай та соки 8 год.'), ('water_only', 'Пити лише воду'), ('no_medications', 'Не приймати ліки перед аналізом'), ('consult_medications', 'Узгодити прийом ліків з лікарем'), ('no_alcohol_24', 'Утриматися від алкоголю 24 год.'), ('no_sport_24', 'Утриматися від фізичних навантажень 24 год.'), ('no_smoking_1h', 'Утриматися від куріння 1 год.'), ('morning_only', 'Прийти вранці (до 11:00)')], max_length=30, null=True, verbose_name='Підготовка'),
        ),
    ]
