# Generated by Django 5.2.7 on 2025-10-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardVaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vaccine', models.DateField(verbose_name='Дата вакцинації')),
                ('reaction', models.CharField(choices=[('Місцева', 'Місцева'), ('Загальна', 'Загальна')], max_length=20, verbose_name='Реакція на щеплення')),
                ('contraindication', models.TextField(max_length=300, verbose_name='Протипоказання')),
                ('product_series', models.CharField(max_length=20, verbose_name='Серія вакцини')),
            ],
            options={
                'verbose_name': 'Щеплень в медичній карті',
                'verbose_name_plural': 'Щеплення в картці',
                'db_table': 'CardVaccine',
            },
        ),
        migrations.CreateModel(
            name='DoctorExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_contacting', models.CharField(max_length=100, verbose_name='Причина звернення')),
                ('cabinet', models.CharField(blank=True, max_length=10, null=True, verbose_name='Кабінет')),
                ('date_visit', models.DateField(verbose_name='Дата прийому')),
                ('report', models.TextField(max_length=1500, verbose_name='Висновки')),
            ],
            options={
                'verbose_name': 'Запис про огляд',
                'verbose_name_plural': 'Записи про огляд',
                'db_table': 'DoctorExamination',
            },
        ),
        migrations.CreateModel(
            name='IndividualMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Значення')),
            ],
            options={
                'verbose_name': 'Індивідуальну позначку',
                'verbose_name_plural': 'Індивідуальні позначки',
                'db_table': 'IndividualMarks',
            },
        ),
        migrations.CreateModel(
            name='MedCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispensary_group', models.BooleanField(default=False, verbose_name='Диспансерна група')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Поставлено на облік')),
                ('deregistration_date', models.DateTimeField(blank=True, null=True, verbose_name='Знято з обліку')),
            ],
            options={
                'verbose_name': 'Медичну карту',
                'verbose_name_plural': 'Медичні картки',
                'db_table': 'MedCard',
            },
        ),
        migrations.CreateModel(
            name='Personnel_MedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата взаємодії')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар про взаємодію/прив’язку')),
            ],
            options={
                'verbose_name': 'Персонал до карти',
                'verbose_name_plural': 'Персонал до карти',
                'db_table': 'PersonnelCard',
            },
        ),
        migrations.CreateModel(
            name='SignalMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Сигнальна позначка')),
            ],
            options={
                'verbose_name': 'Сигнальну позначку',
                'verbose_name_plural': 'Сигнальні позначки',
                'db_table': 'SignalMark',
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Найменування щеплення')),
                ('dose_number', models.PositiveSmallIntegerField(verbose_name='Кількість доз')),
                ('age', models.CharField(max_length=100, verbose_name='Вік для щеплення')),
                ('active_substance', models.CharField(blank=True, max_length=100, null=True, verbose_name='Активна речовина')),
                ('input_method', models.CharField(blank=True, choices=[("Внутрішньом'язова", "Внутрішньом'язова ін'єкція"), ('Підшкірна', "Підшкірна ін'єкція"), ('Внутрішньошкірна', "Внутрішньошкірна ін'єкція"), ('Перорально', 'Перорально(через рот)')], max_length=30, null=True, verbose_name='Cпосіб введення')),
            ],
            options={
                'verbose_name': 'Щеплень',
                'verbose_name_plural': 'Щеплення',
                'db_table': 'Vaccination',
            },
        ),
    ]
