# Generated by Django 5.2.7 on 2025-10-22 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards_app', '0001_initial'),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorexamination',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_app.doctor', verbose_name='Табельний номер лікаря'),
        ),
        migrations.AddField(
            model_name='medcards',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_app.doctor', verbose_name='ID лікаря'),
        ),
        migrations.AddField(
            model_name='medcards',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users_app.patient', verbose_name='ID пацієнта'),
        ),
        migrations.AddField(
            model_name='individualmarks',
            name='medcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards_app.medcards', verbose_name='Номер медичної карти'),
        ),
        migrations.AddField(
            model_name='doctorexamination',
            name='medcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards_app.medcards', verbose_name='Номер медичної карти'),
        ),
        migrations.AddField(
            model_name='cardvaccine',
            name='medcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards_app.medcards', verbose_name='Номер медичної карти'),
        ),
        migrations.AddField(
            model_name='personnel_medcard',
            name='medcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards_app.medcards', verbose_name='Номер медичної карти'),
        ),
        migrations.AddField(
            model_name='personnel_medcard',
            name='personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_app.personnel', verbose_name="Прив'язаний персонал"),
        ),
        migrations.AddField(
            model_name='medcards',
            name='id_med_personnel',
            field=models.ManyToManyField(through='cards_app.Personnel_MedCard', to='users_app.personnel'),
        ),
        migrations.AddField(
            model_name='signalmarks',
            name='id_medcard',
            field=models.ManyToManyField(through='cards_app.IndividualMarks', to='cards_app.medcards'),
        ),
        migrations.AddField(
            model_name='individualmarks',
            name='signal_mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards_app.signalmarks', verbose_name='Cигнальна позначка'),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='id_medcard',
            field=models.ManyToManyField(through='cards_app.CardVaccine', to='cards_app.medcards'),
        ),
        migrations.AddField(
            model_name='cardvaccine',
            name='vaccination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards_app.vaccination', verbose_name='Найменування щеплення'),
        ),
        migrations.AlterUniqueTogether(
            name='individualmarks',
            unique_together={('medcard', 'signal_mark')},
        ),
    ]
