# Generated by Django 5.2.7 on 2025-11-10 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_app', '0002_initial'),
        ('users_app', '0003_familydoctor_date_of_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardvaccine',
            name='vaccination',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='cards_app.vaccination', verbose_name='Найменування щеплення'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctorexamination',
            name='doctor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='users_app.doctor', verbose_name='Табельний номер лікаря'),
            preserve_default=False,
        ),
    ]
